import Head from "next/head";
import Link from "next/link";
import { useContext, useEffect } from "react";
import AuthContext from "../hooks/useAuth";
import Dash from "../components/dash";
import cookie from 'cookie';
import axios from "axios";

export default function Home({user, all_dels, clients}) {

  const {setUser, setClients, setDels} = useContext(AuthContext)

  useEffect(() => {
    setUser(user);
    setClients(clients);
    setDels(all_dels)
  }, [])


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!user ? (  
      <div className="h-screen flex justify-center items-center space-x-20">
        <Link href="/registerpage">
          <a className="text-links text-md font-bold font-inter">Register</a>
        </Link>
        <h1 className="font-bold text-inter text-2xl">|</h1>
        <Link href="/loginpage">
          <a className="text-links text-md font-bold font-inter">Login</a>
        </Link>
      </div> ) : ( <Dash all_dels={all_dels} /> )}
    </div>
  );
}

export let getServerSideProps = async ({ req }) => {
  const res = await axios.get("https://infinidis-maroc-api.herokuapp.com/delivery/deliveries")
  const delis = res.data
  const res2 = await axios.get("https://infinidis-maroc-api.herokuapp.com/delivery/clients")
  const clients = res2.data
  console.log(clients)
  const cookies = cookie.parse(req.headers.cookie);
  if (cookies.refresh) {
    const body = {
      refresh: cookies.refresh,
    };
    const {data}  = await axios.post(
      "https://infinidis-maroc-api.herokuapp.com/users/dj-rest-auth/token/refresh/",
      body
    );
    if ({data} && data.access) {
      console.log(data)
      const userConfig = {
        headers: {
          Authorization: "Bearer " + data.access,
        },
      };
      console.log(userConfig);
      const { data: userData } = await axios.get(
        "https://infinidis-maroc-api.herokuapp.com/users/dj-rest-auth/user/",
        userConfig
      );
      console.log(userData)
      return {
        props: {
          user: userData,
          all_dels: delis,
          clients: clients
        },
      };
    } 
  } else {
    return {
      props: {
        user: [],
        all_dels: delis,
        clients: clients
      },
    };
  } 
};
